r5x: Declare required HALs in FCM
ERROR: files are incompatible: The following instances are in the device manifest but not specified in framework compatibility matrix:
    vendor.egistec.hardware.fingerprint@4.0::IBiometricsFingerprintRbs/default
    vendor.nxp.nxpese@1.0::INxpEse/default
    vendor.nxp.nxpnfc@1.0::INxpNfc/default
Suggested fix:
1. Update deprecated HALs to the latest version.
2. Check for any typos in device manifest or framework compatibility matrices with FCM version >= 3.
3. For new platform HALs, add them to any framework compatibility matrix with FCM version >= 3 where applicable.
4. For device-specific HALs, add to DEVICE_FRAMEWORK_COMPATIBILITY_MATRIX_FILE or DEVICE_PRODUCT_COMPATIBILITY_MATRIX_FILE.: Success